framework:
  secret: '%env(APP_SECRET)%'
  php_errors:
    log: true

  serializer:
    enabled: true
    enable_attributes: true

  validation:
    enabled: true
    enable_attributes: true

when@test:
  framework:
    test: true
    session:
      storage_factory_id: session.storage.factory.mock_file